Automatically come up with the set of libraries to package
Summary:
Automatically come up with the set of libraries to package, instead of explicitly listing them
in `yb_release_manifest.json`.

Test Plan: - `yb_release`

Reviewers: ram, bogdan

Reviewed By: bogdan

Subscribers: eng

Differential Revision: https://phabricator.dev.yugabyte.com/D1245

diff --git a/yb_release b/yb_release
--- a/yb_release
+++ b/yb_release
@@ -1,8 +1,15 @@
 #!/bin/bash
-set -e
-if [[ -z "$DEVOPS_HOME" ]]; then
-  echo "ERROR: DEVOPS_HOME not set" >&2
-  exit 1
+set -euo pipefail
+. ${BASH_SOURCE%/*}/build-support/common-build-env.sh
+
+if [[ -z ${DEVOPS_HOME-} ]]; then
+  devops_home_candidate=$YB_SRC_ROOT/../devops
+  if [[ -d $devops_home_candidate ]]; then
+    DEVOPS_HOME=$devops_home_candidate
+  else
+    echo "ERROR: DEVOPS_HOME not set, and not found at '$devops_home_candidate'" >&2
+    exit 1
+  fi
 fi
 
 if [[ $OSTYPE =~ ^darwin ]]; then
@@ -10,6 +17,7 @@ if [[ $OSTYPE =~ ^darwin ]]; then
   exit 1
 fi
 
-. "$DEVOPS_HOME/bin/"/common.sh
+. "$DEVOPS_HOME/bin/common.sh"
 activate_virtualenv
-"$( dirname "${BASH_SOURCE[0]}" )"/build-support/yb_release.py "$@"
+export PYTHONPATH+=:$YB_SRC_ROOT/python
+"$YB_SRC_ROOT"/build-support/yb_release.py "$@"
