Allow server tarball creation only on CentOS7.
Summary: Check for non-Mac OS for now, can be made just CentOS later.

Test Plan:
Ran on my mac:

16:10 $ ./yb_release
Server tarball is only expected to be built on CentOS7.

PS: We should add an option to arc/phab to ask it not to run jenkin build/tests for such script changes...

Reviewers: ram, karthik

Reviewed By: karthik

Subscribers: karthik, eng

Differential Revision: https://phabricator.dev.yugabyte.com/D1188

diff --git a/yb_release b/yb_release
--- a/yb_release
+++ b/yb_release
@@ -1,7 +1,12 @@
 #!/bin/bash
 set -e
 if [[ -z "$DEVOPS_HOME" ]]; then
-  echo "DEVOPS_HOME not set" >&2
+  echo "ERROR: DEVOPS_HOME not set" >&2
+  exit 1
+fi
+
+if [[ $OSTYPE =~ ^darwin ]]; then
+  echo "ERROR: Server tarball is only expected to be built on CentOS7."
   exit 1
 fi
 
