Better error reporting when running external commands in itest
Summary: Better error reporting when running external commands in itest

Test Plan: run_itest

Reviewers: bogdan, ram, bharat

Reviewed By: bharat

Subscribers: jenkins-bot, devops, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D4789

diff --git a/managed/yb_release b/managed/yb_release
--- a/managed/yb_release
+++ b/managed/yb_release
@@ -1,11 +1,18 @@
 #!/bin/bash
-set -e
-if [[ -z "$DEVOPS_HOME" ]]; then
-  echo "DEVOPS_HOME not set" >&2
-  exit 1
+# Copyright (c) YugaByte, Inc.
+set -euo pipefail
+
+# TODO: move this to common file.
+if [[ -z ${DEVOPS_HOME:-} ]]; then
+  devops_home_candidate_dir="${BASH_SOURCE%/*}"/../devops
+  if [[ -d $devops_home_candidate_dir ]]; then
+    export DEVOPS_HOME=$( cd "$devops_home_candidate_dir" && pwd )
+  else
+    echo "DEVOPS_HOME not set and the devops repo not found at $devops_home_candidate_dir" >&2
+    exit 1
+  fi
 fi
 
 . "$DEVOPS_HOME/bin/"/common.sh
 activate_virtualenv
 "$( dirname "${BASH_SOURCE[0]}" )"/yb_release.py "$@"
-
