[PLAT-19474][Improvement] Ulimit changes are not picked by yb-servers after YNP provisioning for CSPs
Summary: Improvement as enable-linger may not start the user manager. Also added exit code check for loginctl which must succeed.

Test Plan: Manually tested onprem and CSP.

Reviewers: anijhawan, nbhatia, dshubin

Reviewed By: dshubin

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D49807

diff --git a/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2 b/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2
--- a/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2
+++ b/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2
@@ -215,7 +215,10 @@ else
   exit 1
 fi
 
-loginctl enable-linger {{ yb_user }}
+if ! loginctl enable-linger {{ yb_user }}; then
+    echo "Failed to enable linger for user {{ yb_user }}"
+    exit 1
+fi
 
 if [ $? -eq 0 ]; then
   echo "Node agent service installation successful"
