[PLAT-17141] Make node agent installation idempotent for YNP manual provisioning
Summary:
Changes:
1. Always unregister invalid node-agent instead of complaining.
2. Add error message in case the node-agent CLI panics.
3. Report node agent installation failure in YNP.
4. Stop service if it's already running in case of reinstall.

Test Plan:
1. Manually tested several times by deleting some node agent folders, changing UUID, deleting config. node-agent-provision.sh always fixed the issue.
2. Change owner of node-agent to root, deleted the config folder, and then ran node-agent as yugabyte user to cause permission error.

```
[yugabyte@ip-10-9-124-2 ~]$ node-agent
   ⨯ Panic occurred: mkdir /home/yugabyte/node-agent/config: permission denied. Make sure node agent is correctly installed and the right user is running the command.
```

3. Finally, ran
```
./build.sh test
```

Reviewers: anijhawan, svarshney, nbhatia

Reviewed By: svarshney

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D42733

diff --git a/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2 b/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2
--- a/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2
+++ b/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2
@@ -199,10 +199,24 @@ su - {{ yb_user }} -c "\"$installer_dir/node-agent-installer.sh\" -c install \
     --zone_name {{ provider_region_zone_name }} --node_name {{ node_name }} \
     --node_ip {{ node_external_fqdn }} --bind_ip {{ bind_ip }} --silent --skip_verify_cert $airgap_flag"
 
+if [ $? -eq 0 ]; then
+  echo "Node agent installation successful"
+else
+  echo "Error: Node agent installation failed"
+  exit 1
+fi
+
 loginctl enable-linger {{ yb_user }}
 # install node_agent service
 su - {{ yb_user }} -c "\"$installer_dir/node-agent-installer.sh\" -c install_service \
     --user {{ yb_user }}"
+
+if [ $? -eq 0 ]; then
+  echo "Node agent service installation successful"
+else
+  echo "Error: Node agent serviceinstallation failed"
+  exit 1
+fi
 
 if test -f "{{ tmp_directory }}/add_node_to_provider.json"; then
     get_nodes_in_provider=$(_get_nodes_in_provider $yba_url $customer_uuid $provider_id)
