[YNP][PLAT-14664] make node register to provider idempotent
Summary: [YNP] make node register to provider idempotent. Also improves the preflight check for the modules

Test Plan:
Verified that node-agent registration is idempotent.
Verified that preflight checks are successful.

Reviewers: anijhawan, nbhatia

Reviewed By: anijhawan

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D36542

diff --git a/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2 b/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2
--- a/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2
+++ b/managed/node-agent/resources/ynp/modules/provision/node_agent/templates/run.j2
@@ -38,6 +38,13 @@ _add_node_to_provider() {
     echo "${yba_url}/api/v1/customers/${customer_uuid}/zones/${zone_uuid}/nodes"
 }
 
+_get_nodes_in_provider() {
+    local yba_url=$1
+    local customer_uuid=$2
+    local provider_uuid=$3
+    echo "${yba_url}/api/v1/customers/${customer_uuid}/providers/${provider_uuid}/nodes/list"
+}
+
 _get_headers() {
     local token=$1
     echo "Accept: application/json"
@@ -184,54 +191,79 @@ su - {{ yb_user }} -c "\"$installer_dir/node-agent-installer.sh\" -c install -u 
 "$installer_dir/node-agent-installer.sh" -c install_service --user yugabyte
 
 if test -f "{{ tmp_directory }}/add_node_to_provider.json"; then
-    get_provider_endpoint=$(_get_provider_url $yba_url $customer_uuid $provider_id)
-    # Perform GET request to fetch provider data by UUID
-    response=$(curl -s -w "%{http_code}" -o response.txt -X GET "${header_options[@]}" $tls_verify_option "$get_provider_endpoint")
+    get_nodes_in_provider=$(_get_nodes_in_provider $yba_url $customer_uuid $provider_id)
+    # Perform GET request to fetch all the nodes associated with provider
+    response=$(curl -s -w "%{http_code}" -o response.txt -X GET "${header_options[@]}" $tls_verify_option "$get_nodes_in_provider")
     http_status="${response:(-3)}"
     response_body=$(<response.txt)
-
+    matched=false
     # Check if HTTP status code indicates success (2xx range)
     if [ "$http_status" -ge 200 ] && [ "$http_status" -lt 300 ]; then
         echo "HTTP GET request successful. Processing response..."
 
-        # Initialize zone_uuid as empty
-        zone_uuid=""
-
-        # Save the response to a temporary file
-        echo "$response_body" > temp_response.txt
-
-        # Use a while loop with a file to avoid subshell
-        while read -r zone; do
-            zone_code=$(echo "$zone" | grep -oP '"code":\s*"\K[^"]+')
-            uuid=$(echo "$zone" | grep -oP '"uuid":\s*"\K[^"]+')
-
-            if [ "$zone_code" == "{{ provider_region_zone_name }}" ]; then
-                zone_uuid="$uuid"
-                echo "Match found: Zone Code = $zone_code, UUID = $zone_uuid"
+        # Extract IPs using sed and grep
+        ips=$(echo "$response_body" | sed -n 's/.*"ip":"\([^"]*\)".*/\1/p')
+        for ip in $ips; do
+            if [[ "$ip" == "{{ node_ip }}" ]]; then
+                matched=true
                 break
             fi
-        done < <(grep -oP '"zones":\s*\[[^]]*\]' temp_response.txt | grep -oP '{[^}]*}')
+        done
+    else
+        echo "Error: GET request failed with HTTP status $http_status"
+        exit 1
+    fi
 
-        # Check if zone_uuid was found
-        if [ -z "$zone_uuid" ]; then
-            echo "Zone with code {{ provider_region_zone_name }} not found"
-            exit 1
-        fi
-
-        add_node_data=$(cat "{{ tmp_directory }}/add_node_to_provider.json")
-        add_node_url=$(_add_node_to_provider $yba_url $customer_uuid $zone_uuid)
-        response=$(curl -s -w "%{http_code}" -o response.txt -X POST "${header_options[@]}" -d "$add_node_data" $tls_verify_option "$add_node_url")
+    if [[ "$matched" == false ]]; then
+        get_provider_endpoint=$(_get_provider_url $yba_url $customer_uuid $provider_id)
+        # Perform GET request to fetch provider data by UUID
+        response=$(curl -s -w "%{http_code}" -o response.txt -X GET "${header_options[@]}" $tls_verify_option "$get_provider_endpoint")
         http_status="${response:(-3)}"
+        response_body=$(<response.txt)
 
-        if [ $http_status -ge 200 ] && [ $http_status -lt 300 ]; then
-            echo "Node added successfully"
+        # Check if HTTP status code indicates success (2xx range)
+        if [ "$http_status" -ge 200 ] && [ "$http_status" -lt 300 ]; then
+            echo "HTTP GET request successful. Processing response..."
+
+            # Initialize zone_uuid as empty
+            zone_uuid=""
+
+            # Save the response to a temporary file
+            echo "$response_body" > temp_response.txt
+
+            # Use a while loop with a file to avoid subshell
+            while read -r zone; do
+                zone_code=$(echo "$zone" | grep -oP '"code":\s*"\K[^"]+')
+                uuid=$(echo "$zone" | grep -oP '"uuid":\s*"\K[^"]+')
+
+                if [ "$zone_code" == "{{ provider_region_zone_name }}" ]; then
+                    zone_uuid="$uuid"
+                    echo "Match found: Zone Code = $zone_code, UUID = $zone_uuid"
+                    break
+                fi
+            done < <(grep -oP '"zones":\s*\[[^]]*\]' temp_response.txt | grep -oP '{[^}]*}')
+
+            # Check if zone_uuid was found
+            if [ -z "$zone_uuid" ]; then
+                echo "Zone with code {{ provider_region_zone_name }} not found"
+                exit 1
+            fi
+
+            add_node_data=$(cat "{{ tmp_directory }}/add_node_to_provider.json")
+            add_node_url=$(_add_node_to_provider $yba_url $customer_uuid $zone_uuid)
+            response=$(curl -s -w "%{http_code}" -o response.txt -X POST "${header_options[@]}" -d "$add_node_data" $tls_verify_option "$add_node_url")
+            http_status="${response:(-3)}"
+
+            if [ $http_status -ge 200 ] && [ $http_status -lt 300 ]; then
+                echo "Node added successfully"
+            else
+                echo "Error: POST request failed with HTTP status $http_status"
+                exit 1
+            fi
         else
             echo "Error: POST request failed with HTTP status $http_status"
             exit 1
         fi
-    else
-        echo "Error: POST request failed with HTTP status $http_status"
-        exit 1
     fi
 fi
 
