[PLAT-19474] Ulimit changes are not picked by yb-servers after YNP provisioning for CSPs
Summary: Restart the systemd --user service to pick up the ulimits without rebooting.

Test Plan:
Manually tested on both CSPs and onprem (alma 9, ubuntu 22, SLES-SP5)

```
[yugabyte@ip-10-9-64-243 ~]$ systemctl --user status yb-master
● yb-master.service - Yugabyte master service
     Loaded: loaded (/home/yugabyte/.config/systemd/user/yb-master.service; enabled; preset: disabled)
     Active: active (running) since Fri 2026-01-16 23:39:00 UTC; 1min 13s ago
   Main PID: 18654 (yb-master)
      Tasks: 25 (limit: 22414)
     Memory: 82.0M
        CPU: 1.577s
     CGroup: /user.slice/user-1994.slice/user@1994.service/app.slice/yb-master.service
             └─18654 /home/yugabyte/master/bin/yb-master --flagfile /home/yugabyte/master/conf/server.conf

Jan 16 23:39:00 ip-10-9-64-243.us-west-2.compute.internal systemd[16034]: Starting Yugabyte master service...
Jan 16 23:39:00 ip-10-9-64-243.us-west-2.compute.internal clock-sync.sh[18632]: Waiting for mount points to be mounted: /mnt/d0
Jan 16 23:39:00 ip-10-9-64-243.us-west-2.compute.internal clock-sync.sh[18632]: All mount points are mounted.
Jan 16 23:39:00 ip-10-9-64-243.us-west-2.compute.internal clock-sync.sh[18632]: Clock skew is within acceptable limits: 0.000010976 ms
Jan 16 23:39:00 ip-10-9-64-243.us-west-2.compute.internal clock-sync.sh[18632]: Success! Clock skew is within acceptable limits.
Jan 16 23:39:00 ip-10-9-64-243.us-west-2.compute.internal systemd[16034]: Started Yugabyte master service.
[yugabyte@ip-10-9-64-243 ~]$ cat /proc/18654/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              8388608              bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             12000                12000                processes
Max open files            1048576              1048576              files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       119934               119934               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

Reviewers: anijhawan, dshubin, nbhatia

Reviewed By: anijhawan

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D49704

diff --git a/managed/node-agent/resources/ynp/modules/provision/systemd/templates/run.j2 b/managed/node-agent/resources/ynp/modules/provision/systemd/templates/run.j2
--- a/managed/node-agent/resources/ynp/modules/provision/systemd/templates/run.j2
+++ b/managed/node-agent/resources/ynp/modules/provision/systemd/templates/run.j2
@@ -1,9 +1,8 @@
 # Set default system level systemd
 systemd_dir="/etc/systemd/system"
 {% if use_system_level_systemd == 'False' %}
-    # Enable linger for yb_user
-    loginctl enable-linger {{ yb_user }}
-    xdg_runtime_env="export XDG_RUNTIME_DIR=/run/user/$(id -u {{ yb_user }})"
+    runtime_dir="/run/user/$(id -u {{ yb_user }})"
+    xdg_runtime_env="export XDG_RUNTIME_DIR=$runtime_dir"
     if ! grep -qxF "${xdg_runtime_env}" {{yb_home_dir}}/.bashrc >/dev/null 2>&1; then
         su - {{ yb_user }} -c "echo ${xdg_runtime_env} >> {{yb_home_dir}}/.bashrc"
     fi
@@ -12,6 +11,39 @@ systemd_dir="/etc/systemd/system"
     systemd_dir="{{ yb_home_dir }}/.config/systemd/user"
     # Ensure the systemd directory exists
     su - {{ yb_user }} -c "mkdir -p ${systemd_dir}"
+    # Determine the PLATFORM_ID
+    platform_id=$(grep -oP '(?<=^PLATFORM_ID=).+' /etc/os-release | tr -d '"' || echo "unknown")
+    if [[ "$platform_id" == "platform:el8" ]] || [[ "$platform_id" == "platform:el9" ]]; then
+        # Stop user systemd service.
+        su - {{ yb_user }} -c "XDG_RUNTIME_DIR=$runtime_dir systemctl --user exit >/dev/null 2>&1"
+        status_cmd="XDG_RUNTIME_DIR=$runtime_dir systemctl --user status --no-pager >/dev/null 2>&1"
+        count=0
+        # Do in retries as there is a race between stopping and checking status.
+        while su - {{ yb_user }} -c "$status_cmd"; do
+            count=$((count + 1))
+            if [ $count -gt 10 ]; then
+                echo "User systemd service failed to stop after $count attempts."
+                exit 1
+            fi
+            echo "Waiting for user systemd service to stop..."
+            sleep 2
+        done
+        count=0
+        # Do in retries as there is a race between stopping and enabling linger.
+        until su - {{ yb_user }} -c "$status_cmd"; do
+            # Enable linger for yb_user
+            loginctl enable-linger {{ yb_user }}
+            count=$((count + 1))
+            if [ $count -gt 10 ]; then
+                echo "User systemd service failed to start after $count attempts."
+                exit 1
+            fi
+            echo "Waiting for user system service to become active..."
+            sleep 2
+        done
+    else
+      loginctl enable-linger {{ yb_user }}
+    fi
 {% endif %}
 
 # Configure the systemd unit files
