[PLAT-19661] Unify node level pre-checks to always use YNP pre-flight checks
Summary:
This unifies onprem manual prechecks into YNP prechecks. If the provider is non-manual and onprem, devops prechecks are still used because there is no YNP installed.
How it works:
1. Common generator shared code for YNPProvisioning, Detached prechecks and Universe node prechecks.
2. YBA <-> Node agent interacts via new RPC. YBA sends the JSON string as input. Node agent locally writes to a file and launches the precheck.
3. Stdout and stderr are sent back to YBA for observability and debugging.
4. More checks like port available checks, space checks are added. Port check is only used for this YBA triggered precheck on the first run. Manual node-agent-provision.sh cannot use due to idempotency issue. So, it is disabled in this case.
5. Disk space thresholds are still exposed on YBA that are passed to node-agent for convenience.
6. Known, fixed values like ulimits are deprecated on YBA as they are not needed anymore.

Test Plan:
Manually tested the scenarios:
1. Run a python http server on 7000 and run detached precheck. It fails as expected.

```

    {
      "check": "Port 9300 Check",
      "result": "FAIL",
      "message": "Port 9300 is unavailable on 10.9.96.53"
    },
    {
      "check": "Port 7000 Check",
      "result": "PASS",
      "message": "Port 7000 is available on 10.9.96.53"
    },
    {
....

    },
    {
      "check": "Port 5433 Check",
      "result": "PASS",
      "message": "Port 5433 is open on 10.9.96.53"
    }
]}
Pre-flight checks failed, Please fix them before continuing.
```

2. Stop the server. It passes as expected.

```
    {
      "check": "Port 12000 Check",
      "result": "PASS",
      "message": "Port 12000 is open on 10.9.96.53"
    },
    {
      "check": "Port 9042 Check",
      "result": "PASS",
      "message": "Port 9042 is open on 10.9.96.53"
    },
    {
      "check": "Port 13000 Check",
      "result": "PASS",
      "message": "Port 13000 is open on 10.9.96.53"
    },
    {
      "check": "Port 5433 Check",
      "result": "PASS",
      "message": "Port 5433 is open on 10.9.96.53"
    }
]}
Pre-flight checks successful
```

3. Create onprem universe that internally runs non-detached precheck. It passes.

4. Create aws universe to make sure the path is not broken. It passes.

5. YNPProvisioningTest internally tests YNPConfigGenerator. All UTs pass.

6. Turn off this feature to make sure legacy check still works. It passes.

7. UI screen for failure.
{F458383}

Reviewers: anijhawan, spothuraju, skhilar, nbhatia, yshchetinin

Reviewed By: spothuraju

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D50614

diff --git a/managed/node-agent/resources/ynp/modules/provision/network/templates/precheck.j2 b/managed/node-agent/resources/ynp/modules/provision/network/templates/precheck.j2
--- a/managed/node-agent/resources/ynp/modules/provision/network/templates/precheck.j2
+++ b/managed/node-agent/resources/ynp/modules/provision/network/templates/precheck.j2
@@ -3,7 +3,10 @@
 #       if there are any other firewalls,configured this will need to be
 #       verified from Yugabyte Anywhere or outside the universe from the client side.
 #
-ports=({{ports}})
+ports=({{node_exporter_port}} {{master_http_port}} {{master_rpc_port}} {{tserver_http_port}} \
+{{tserver_rpc_port}} {{yb_controller_http_port}} {{yb_controller_rpc_port}} {{redis_server_http_port}} \
+{{redis_server_rpc_port}} {{ycql_server_http_port}} {{ycql_server_rpc_port}} {{ysql_server_http_port}} \
+{{ysql_server_rpc_port}})
 
 
 # IP address of the VM (assuming localhost)
@@ -22,8 +25,16 @@ start_server() {
 check_port() {
     local ip=$1
     local port=$2
-    (echo > /dev/tcp/$ip/$port) >/dev/null 2>&1
-    if [ $? -eq 0 ]; then
+    count=0
+    # Start checking the port to respond faster for reachable ports.
+    until "echo > /dev/tcp/$ip/$port" >/dev/null 2>&1; do
+        count=$((count + 1))
+        if [ $count -gt 5 ]; then
+            break
+        fi
+        sleep 0.5
+    done
+    if [ $count -le 5 ]; then
         echo "Port $port is open on $ip"
         add_result "Port $port Check" "PASS" "Port $port is open on $ip"
     else
@@ -50,19 +61,51 @@ force_kill_on_exit() {
     fi
 }
 
+check_port_available() {
+  ip=$1
+  port=$2
+  if ss -lntu | grep -q ":$port\s" >/dev/null 2>&1; then
+    echo "Port $port is unavailable on $ip"
+    add_result "Port $port Check" "FAIL" "Port $port is unavailable on $ip"
+  else
+    echo "Port $port is available on $ip"
+    add_result "Port $port Check" "PASS" "Port $port is available on $ip"
+  fi
+}
+
+# Check for internet access.
+if [[ "{{ is_airgap }}" == 'False' ]]; then
+    # Attempt to run "/dev/tcp" 3 times with a 3 second timeout and return success if any succeed.
+    # --preserve-status flag will maintain the exit code of the "/dev/tcp" command.
+    HOST="yugabyte.com"
+    PORT=443
+
+    for i in 1 2 3; do
+      timeout 5 bash -c "cat < /dev/null > /dev/tcp/${HOST}/${PORT}" --preserve-status && break
+    done
+    if [[ $? -ne 0 ]]; then
+        add_result "Internet Connection" "FAIL" "Internet connection check failed for non-airgap environment"
+    else
+        add_result "Internet Connection" "PASS" "Internet connection check passed for non-airgap environment"
+    fi
+fi
+
+# Optional check for available ports. Cannot be run if the services are expected to be up.
+if [ "{{ check_available_ports }}" == "True" ]; then
+    for port in "${ports[@]}"; do
+        # Node exporter is already running. Skip its port.
+        [ "$port" -ne "{{node_exporter_port}}" ] && check_port_available "$vm_ip" "$port"
+    done
+fi
 
 # Iterate through the list of ports, start server, check port, and stop server
-if [ "$is_cloud" == "False" ]; then
+if [ "$cloud_type" == "onprem" ]; then
     for port in "${ports[@]}"; do
         # Start the server and get its PID
         server_pid=$(start_server $port)
         if [ -n "$server_pid" ]; then
             trap "force_kill_on_exit $server_pid" EXIT
         fi
-
-        # Give the server a moment to start
-        sleep 2
-
         # Check if the port is open
         check_port "$vm_ip" "$port"
 
