[BACKPORT 2026.1][PLAT-20506] Add an automated way for Wells Fargo to change the installation directory from their custom directory to yugabyte user's home directory
Summary:
Original diffs:
https://phorge.dev.yugabyte.com/D52247 (64fb0bbb418635658aa90eb1c32e29f69cb40bdc)
https://phorge.dev.yugabyte.com/D52654 (b463f61686d476981c285f81f0dc2fa567e728bc)

1. Add a separate yb_user_home for yugabyte user.
2. Use the existing yb_home_dir for software. This already works because cron works with this. All the node agent actions/tasks use this. So, no change in existing functionality.
3. Add an internal runtime config for yb_home_user override for easy tests.

Test Plan:
1. Manually tested with CSPs and onprem.
2. Tested generate config, config override.
3. Health checks are green.

Onprem manual

{F477504}

CSPs

{F477505}

Reviewers: anijhawan, nbhatia, spothuraju, skhilar, vkumar, yshchetinin

Reviewed By: spothuraju

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D52571

diff --git a/managed/node-agent/resources/templates/server/yb-tserver-cgroup-exec.sh.j2 b/managed/node-agent/resources/templates/server/yb-tserver-cgroup-exec.sh.j2
--- a/managed/node-agent/resources/templates/server/yb-tserver-cgroup-exec.sh.j2
+++ b/managed/node-agent/resources/templates/server/yb-tserver-cgroup-exec.sh.j2
@@ -7,8 +7,23 @@
 
 set -euo pipefail
 
-YB_HOME="{{ yb_home_dir }}"
-STATE_DIR="${YB_HOME}/.yugabyte"
+find_yb_user_home() {
+  if id -u "yugabyte" >/dev/null 2>&1; then
+    yb_user_home=$(getent passwd yugabyte | cut -d: -f6 2>&1)
+    if [[ -z "$yb_user_home" ]]; then
+      echo "FATAL: Could not find home directory for user yugabyte"
+      exit 1
+    else
+      echo "$yb_user_home"
+    fi
+  else
+    echo "FATAL: User yugabyte does not exist"
+    exit 1
+  fi
+}
+
+YB_USER_HOME=$(find_yb_user_home)
+STATE_DIR="${YB_USER_HOME}/.yugabyte"
 CG_NAME="yugabyte-db"
 
 # Read cgroup type from state file
