bp ref

diff --git a/.github/workflows/pull_checks.yml b/.github/workflows/pull_checks.yml
--- a/.github/workflows/pull_checks.yml
+++ b/.github/workflows/pull_checks.yml
@@ -56,4 +56,23 @@ jobs:
               exit 1
             fi
           fi
-          # Check if there is backport commit/PR info in desc.
+
+      - name: Check Backport refernces
+        run: |
+          # Check for true backport, not just target branch in title.
+          BACKPORT_RE='^\[BACKPORT ([0-9]+(\.[0-9]+)+)\]'
+          if [[ "${{ github.event.pull_request.title }}" =~ $BACKPORT_RE ]]; then
+            COMMIT_RE='^Original commit: ([0-9a-f]+) / ([#D][0-9]+)'
+            body="${{ github.event.pull_request.body }}"
+            if ! echo "$body" | grep -qE "$COMMIT_RE"; then
+              echo "::error ::Backport PR must include original commit SHA and issue reference"
+              echo "::error ::in the PR description. Examples:"
+              echo "::error ::Original commit: 123abc / #12345"
+              echo "::error ::Original commits:"
+              echo "::error ::- 123abc / #12345"
+              echo "::error ::- 345def / #43555"
+              exit 1
+            fi
+    #original_commit_re = Regexp.new('^Original commit(s)?:')
+    #commit_sha_revision_re = Regexp.new('(^- )?([0-9a-f]+) / ([#D][0-9]+)')
+          fi
