Run sql tests without caching container

diff --git a/.github/workflows/regress_tests.yml b/.github/workflows/regress_tests.yml
--- a/.github/workflows/regress_tests.yml
+++ b/.github/workflows/regress_tests.yml
@@ -11,27 +11,76 @@ on:
       - 'main'
     paths-ignore:
       - 'docs/**'
-      - '.github/containers/**'
       - '.devcontainer/**'
       - '*.md'
   pull_request:
-    types: [opened, reopened,synchronize]
+    types: [opened, reopened, synchronize]
     paths-ignore:
       - 'docs/**'
-      - '.github/containers/**'
       - '.devcontainer/**'
       - '*.md'
-  merge_group:
 
 jobs:
-  ubuntu_build:
+  runs-on: ubuntu-latest
+  steps:
+    - name: Checkout repository
+      uses: actions/checkout@v3
 
-    runs-on: ubuntu-latest
-    container:
-      image: ghcr.io/safern/heliodb/build_ubuntu:safern-setup_build_action_latest
+    - name: Set up dependencies
+      run: |
+        sudo apt-get update && export DEBIAN_FRONTEND=noninteractive \
+          && sudo apt-get install -qy \
+          wget \
+          curl \
+          sudo \
+          gnupg2 \
+          lsb-release \
+          tzdata \
+          build-essential \
+          pkg-config \
+          cmake \
+          git \
+          && sudo rm -rf /var/lib/apt/lists/*
 
-    steps:
-    - uses: actions/checkout@v4
+    - name: Add PostgreSQL repo
+      run: |
+        echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list && \
+        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - && \
+        sudo apt-get update && \
+        sudo rm -rf /var/lib/apt/lists/*
+
+    - name: Add CitusData repo
+      run: |
+        curl -4sSf https://packagecloud.io/install/repositories/citusdata/community/script.deb.sh | sudo bash
+
+    - name: Install PostgreSQL and Extensions
+      run: |
+        sudo apt-get update && export DEBIAN_FRONTEND=noninteractive \
+          && sudo apt-get install -y \
+          postgresql-16 \
+          postgresql-server-dev-16 \
+          libpq-dev \
+          postgresql-16-pgcron \
+          postgresql-16-pgvector \
+          postgresql-16-postgis-3 \
+          postgresql-16-rum \
+          && sudo rm -rf /var/lib/apt/lists/*
+
+    - name: Install Additional Libraries
+      run: |
+        export CLEANUP_SETUP=1
+        export INSTALL_DEPENDENCIES_ROOT=/tmp/install_setup
+        sudo mkdir -p /tmp/install_setup
+        sudo cp -r scripts/ /tmp/install_setup
+        sudo MAKE_PROGRAM=cmake /tmp/install_setup/install_setup_libbson.sh
+        sudo /tmp/install_setup/install_setup_pcre2.sh
+        sudo /tmp/install_setup/install_setup_intel_decimal_math_lib.sh
+        sudo /tmp/install_setup/install_citus_indent.sh
+
+    - name: Clean up and Set Locale
+      run: |
+        sudo rm -rf /var/lib/apt/lists/* \
+          && sudo localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
 
     - name: Build and install
       run: sudo make install
@@ -41,4 +90,4 @@ jobs:
 
     - name: Citus Indent
       run: |
-        citus_indent --check || (echo ""; echo "citus_indent failed, refer to CONTRIBUTING.md on how to use citus_indent"; exit 1)
+        citus_indent --check || (echo ""; echo "citus_indent failed, refer to CONTRIBUTING.md on how to use citus_indent"; exit 1)    
